repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
        args: ['--maxkb=900']
    -   id: detect-private-key
-   repo: https://github.com/psf/black
    rev: 21.5b1
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/flake8
    rev: '3.9.2'
    hooks:
    -   id: flake8
        args: ['--max-complexity=10', '--max-line-length=105', '--extend-ignore=E203']
-   repo: https://github.com/timothycrosley/isort
    rev: 5.7.0
    hooks:
      - id: isort
        additional_dependencies: [toml]
        exclude: ^.*/?setup\.py$
        args: ["--profile", "black"]
